[project]
name = "aoc"
version = "0.1.0"
description = "My solutions to Advent of Code"
requires-python = ">=3.11"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.9.3",
    "numpy>=2.1.3",
    "parse>=1.20.2",
]
